Change optionalModules to modules as checkout location
LabKey/immport pull request #11
Opened 2020-05-08 18:30 UTC by labkey-ians

Rationale
Consolidate to server/modules as the preferred location for building module code

Related Pull Requests
https://github.com/LabKey/platform/pull/1155

Changes
Update README

2020-05-08 18:40 UTC, labkey-susanh approved these changes

2020-05-11 20:15 UTC, labkey-tchad requested changes
Do we need to remove the plugin application here to avoid a conflict from `server/modules` attempting to apply the same plugin again?

2020-05-11 20:26 UTC, labkey-susanh commented
> Do we need to remove the plugin application here to avoid a conflict from `server/modules` attempting to apply the same plugin again?

Good question, and it now makes me wonder why Gradle doesn't complain about this when I build locally. And why isn't it complaining about the use of the compile and apiCompile configurations here either?

2020-05-13 15:14 UTC, labkey-tchad approved these changes

2020-05-13 16:20 UTC, merged