customize datafinder url
LabKey/immport pull request #5
Opened 2020-03-10 17:34 UTC by labkey-matthewb

2020-03-10 20:59 UTC, labkey-adam requested changes
Change import. Other comments optional.

2020-03-10 20:59 UTC, labkey-adam commented on src/org/labkey/immport/ImmPortModule.java
> +import static com.rometools.utils.Strings.isBlank;
Wrong import, I suspect

2020-03-10 20:59 UTC, labkey-adam commented on src/org/labkey/immport/ImmPortModule.java
> +        ImmPortModule m = (ImmPortModule)ModuleLoader.getInstance().getModule("immport");
"immport" -> NAME?

2020-03-10 20:59 UTC, labkey-adam commented on src/org/labkey/immport/ImmPortModule.java
> +        ModuleProperty studyFinder = new ModuleProperty(this, "dataFinderUri", ModuleProperty.InputType.text, "URL for data finder, default /Studies/project-begin.view", "datafinder url", true)
Constant for "dataFinderUri"?

2020-03-11 20:46 UTC, labkey-matthewb commented on src/org/labkey/immport/ImmPortModule.java
> +import static com.rometools.utils.Strings.isBlank;
thank you

2020-03-12 19:05 UTC, labkey-adam approved these changes

2020-03-12 20:07 UTC, merged